sudo: required
services:
    - docker

before_install:
    - docker build -t searhiy/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true searhiy/docker-react npm run test -- --coverage